### ISSUE TITLE
An internal error occurred during: "Initializing Java Tooling". -?>> does not exist

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#553]
Original [issue 512](https://code.google.com/p/counterclockwise/issues/detail?id=512) created by laurentpetit on 2013-01-23T18:17:59.000Z:

<b>What steps will reproduce the problem?</b>
1. just starting eclipse but it only happens sometimes
2. this was happening before but I was ignoring it
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
An internal error occurred during: &quot;Initializing Java Tooling&quot;.
-?&gt;&gt; does not exist

Message:
An internal error occurred during: &quot;Initializing Java Tooling&quot;.

Plug-in:
org.eclipse.core.jobs

Exception Stack Trace:
java.lang.IllegalAccessError: -?&gt;&gt; does not exist
    at clojure.core$refer.doInvoke(core.clj:3826)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_lib.doInvoke(core.clj:5371)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$use.doInvoke(core.clj:5484)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at ccw.leiningen.classpath_container$eval418$loading__4929__auto____419.invoke(classpath_container.clj:1)
    at ccw.leiningen.classpath_container$eval418.invoke(classpath_container.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6603)
    at clojure.lang.Compiler.eval(Compiler.java:6592)
    at clojure.lang.Compiler.load(Compiler.java:7047)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.loadResourceScript(RT.java:352)
    at clojure.lang.RT.load(RT.java:431)
    at clojure.lang.RT.load(RT.java:402)
    at clojure.osgi.ClojureOSGi$4.run(ClojureOSGi.java:127)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.load(ClojureOSGi.java:125)
    at clojure.osgi.core$osgi_load.invoke(core.clj:40)
    at clojure.osgi.core$eval17$fn__18$fn__19.invoke(core.clj:50)
    at clojure.core$load_one.invoke(core.clj:5313)
    at clojure.core$load_lib$fn__4986.invoke(core.clj:5352)
    at clojure.core$load_lib.doInvoke(core.clj:5351)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5473)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.osgi.core$osgi_require.invoke(core.clj:78)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.osgi.ClojureOSGi$1.run(ClojureOSGi.java:65)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.require(ClojureOSGi.java:63)
    at ccw.util.BundleUtils.requireAndGetVar(BundleUtils.java:36)
    at ccw.util.GenericExecutableExtension.initFactory(GenericExecutableExtension.java:69)
    at ccw.util.GenericExecutableExtension.setInitializationData(GenericExecutableExtension.java:47)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:251)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3175)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3151)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2824)
    at org.eclipse.jdt.internal.core.JavaModelManager$11.run(JavaModelManager.java:2749)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:2789)
    at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1873)
    at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:3886)
    at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:36)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

<b>What version of the product are you using? On what operating system?</b>
eclipse.buildId=M20120914-1800
java.version=1.6.0_33
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

<b>Please provide any additional information below.</b>
workspace java ver:
java version &quot;1.7.0_09&quot;
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)

the java which I use to run eclipse with:
java version &quot;1.6.0_33&quot;
Java(TM) SE Runtime Environment (build 1.6.0_33-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.8-b03, mixed mode)

eclipse.ini file:
-vm
C:/Program Files/Java/jre6/bin/javaw.exe
-startup
plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20120522-1813
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
-vmargs
-Duser.name=whatever
-Dfile.encoding=UTF-8
-Dosgi.requiredJavaVersion=1.5
-XX:+HeapDumpOnOutOfMemoryError
-Dcom.sun.management.jmxremote
-Xms228m
-Xmx712m
-XX:MaxPermSize=256m

Eclipse SDK

Version: 4.2.1
Build id: M20120914-1800
win7 64bit
  Counterclockwise (Clojure plugin for Eclipse) 0.11.1.201301102206 ccw.feature.feature.group   Counterclockwise team
    Leiningen Support   0.11.1.201301102206 ccw.leiningen.feature.feature.group Counterclockwise team
# 

After this, I closed and started eclipse again, then I got 2 different errors instead, but still related to &quot;-?&gt;&quot;

Message:
Error in JDT Core during reconcile

Plugin:
org.eclipse.jdt.ui

Exception Stack Trace:
java.lang.IllegalAccessError: -?&gt; does not exist
    at clojure.core$refer.doInvoke(core.clj:3826)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_lib.doInvoke(core.clj:5371)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$use.doInvoke(core.clj:5484)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at ccw.leiningen.classpath_container$eval406$loading__4929__auto____407.invoke(classpath_container.clj:1)
    at ccw.leiningen.classpath_container$eval406.invoke(classpath_container.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6603)
    at clojure.lang.Compiler.eval(Compiler.java:6592)
    at clojure.lang.Compiler.load(Compiler.java:7047)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.loadResourceScript(RT.java:352)
    at clojure.lang.RT.load(RT.java:431)
    at clojure.lang.RT.load(RT.java:402)
    at clojure.osgi.ClojureOSGi$4.run(ClojureOSGi.java:127)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.load(ClojureOSGi.java:125)
    at clojure.osgi.core$osgi_load.invoke(core.clj:40)
    at clojure.osgi.core$eval17$fn__18$fn__19.invoke(core.clj:50)
    at clojure.core$load_one.invoke(core.clj:5313)
    at clojure.core$load_lib$fn__4986.invoke(core.clj:5352)
    at clojure.core$load_lib.doInvoke(core.clj:5351)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5473)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.osgi.core$osgi_require.invoke(core.clj:78)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.osgi.ClojureOSGi$1.run(ClojureOSGi.java:65)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.require(ClojureOSGi.java:63)
    at ccw.util.BundleUtils.requireAndGetVar(BundleUtils.java:36)
    at ccw.util.GenericExecutableExtension.initFactory(GenericExecutableExtension.java:69)
    at ccw.util.GenericExecutableExtension.setInitializationData(GenericExecutableExtension.java:47)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:251)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3175)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3151)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2824)
    at org.eclipse.jdt.internal.core.JavaModelManager$11.run(JavaModelManager.java:2749)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:2789)
    at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1873)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3128)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2691)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2855)
    at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1960)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:638)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:707)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:671)
    at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1429)
    at org.eclipse.jdt.internal.core.JavaProjectElementInfo.getProjectCache(JavaProjectElementInfo.java:206)
    at org.eclipse.jdt.internal.core.JavaProjectElementInfo.newNameLookup(JavaProjectElementInfo.java:290)
    at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2327)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.&lt;init&gt;(SearchableEnvironment.java:59)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.&lt;init&gt;(SearchableEnvironment.java:66)
    at org.eclipse.jdt.internal.core.CancelableNameEnvironment.&lt;init&gt;(CancelableNameEnvironment.java:26)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:176)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:269)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:190)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:89)
    at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:728)
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:788)
    at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1247)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:126)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:108)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:89)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:178)
    at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:114)
    at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:136)
    at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:105)
    at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:406)
    at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:173)

and this one:
Message:
Problems occurred when invoking code from plug-in: &quot;org.eclipse.jdt.ui&quot;.

Plugin:
org.eclipse.jdt.ui

Exception Stack Trace:
java.lang.IllegalAccessError: -?&gt; does not exist
    at clojure.core$refer.doInvoke(core.clj:3826)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_lib.doInvoke(core.clj:5371)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$use.doInvoke(core.clj:5484)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at ccw.leiningen.classpath_container$eval406$loading__4929__auto____407.invoke(classpath_container.clj:1)
    at ccw.leiningen.classpath_container$eval406.invoke(classpath_container.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6603)
    at clojure.lang.Compiler.eval(Compiler.java:6592)
    at clojure.lang.Compiler.load(Compiler.java:7047)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.loadResourceScript(RT.java:352)
    at clojure.lang.RT.load(RT.java:431)
    at clojure.lang.RT.load(RT.java:402)
    at clojure.osgi.ClojureOSGi$4.run(ClojureOSGi.java:127)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.load(ClojureOSGi.java:125)
    at clojure.osgi.core$osgi_load.invoke(core.clj:40)
    at clojure.osgi.core$eval17$fn__18$fn__19.invoke(core.clj:50)
    at clojure.core$load_one.invoke(core.clj:5313)
    at clojure.core$load_lib$fn__4986.invoke(core.clj:5352)
    at clojure.core$load_lib.doInvoke(core.clj:5351)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5390)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5473)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.osgi.core$osgi_require.invoke(core.clj:78)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.osgi.ClojureOSGi$1.run(ClojureOSGi.java:65)
    at clojure.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:158)
    at clojure.osgi.ClojureOSGi.require(ClojureOSGi.java:63)
    at ccw.util.BundleUtils.requireAndGetVar(BundleUtils.java:36)
    at ccw.util.GenericExecutableExtension.initFactory(GenericExecutableExtension.java:69)
    at ccw.util.GenericExecutableExtension.setInitializationData(GenericExecutableExtension.java:47)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:251)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3175)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3151)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2824)
    at org.eclipse.jdt.internal.core.JavaModelManager$11.run(JavaModelManager.java:2749)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:2789)
    at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1873)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3128)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2691)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2855)
    at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1960)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:638)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:707)
    at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:671)
    at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1429)
    at org.eclipse.jdt.internal.core.JavaProjectElementInfo.getProjectCache(JavaProjectElementInfo.java:206)
    at org.eclipse.jdt.internal.core.JavaProjectElementInfo.newNameLookup(JavaProjectElementInfo.java:290)
    at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2327)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.&lt;init&gt;(SearchableEnvironment.java:59)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.&lt;init&gt;(SearchableEnvironment.java:66)
    at org.eclipse.jdt.internal.core.CancelableNameEnvironment.&lt;init&gt;(CancelableNameEnvironment.java:26)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:176)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:269)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:190)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:89)
    at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:728)
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:788)
    at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1247)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:126)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:108)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:89)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:178)
    at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:114)
    at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:136)
    at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:105)
    at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:406)
    at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:173)

And now, the second time I close eclipse and start it again (so started it 3rd time, since 1st time it wasn't closed, but just started after computer booted up), there were no errors and I didn't change anything.

The 4th time I close and start eclipse, after I manually deleted all errors in Error Log view, the two errors pop-ed again. Then I left them and restarted for the 5th time, they remained with their Data not updated and no new errors appeared. Then deleted the Error Log again, restarted for 6th time and they still didn't re-apear. Then deleted the error log again, since there was one from rabbit plugin with some 5 sec timeout, if you want to know it was this:

and I cannot include more text because when I do Submit issue it says in red &quot;Comment is too long&quot;
but you can see the rest here: https://gist.github.com/59da7415b61a4ae4f0ff

**Comment by Parthan-Akon** [comment]
The solutions is to just delete your existing server and create a new server and run the application once again.. The error will be gone
