### ISSUE TITLE
Error trying to edit a Clojure source file, after upgrading to v0.31.0

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#719]
Original [issue 678](https://code.google.com/p/counterclockwise/issues/detail?id=678) created by laurentpetit on 2014-12-04T17:51:35.000Z:

<b>What steps will reproduce the problem?</b>

After upgrading to CCW plugin for Eclipse v0.31.0 I'm not able to open Clojure source files. It worked after the upgrade and first restart. I closed Eclipse, and I'm not longer able to open Clojure source code.

<b>What is the expected output? What do you see instead?</b>
- I'm expecting to open/edit Clojure source code, instead I'm getting the following message:

Plug-in &quot;ccw.core&quot; was unable to instantiate class &quot;ccw.editors.clojure.ClojureEditor&quot;.

<b>What version of the product are you using? On what operating system?</b>
- Eclipse Java EE IDE for Web Developers - Version: Luna Service Release 1 (4.4.1) - Build id: 20140925-1800
- CCW plugin v0.31.0.STABLE001
- OS: Arch Linux - 3.17.4-1-ARCH #&nbsp;1 SMP PREEMPT Fri Nov 21 21:14:42 CET 2014 x86_64 GNU/Linux
- Java: java version &quot;1.7.0_71&quot; - OpenJDK Runtime Environment (IcedTea 2.5.3) (Arch Linux build 7.u71_2.5.3-1-x86_64)

<b>Please provide any additional information below.</b>
- The events namespace exists under the ccw plugin folder:

$ find plugins/ccw.core_0.31.0.STABLE001/ -name 'events.clj'
plugins/ccw.core_0.31.0.STABLE001/ccw/events.clj
- The previous version of the plugin is still there, not sure if this is the cause of the problem.
  $ ls plugins/ccw.core_0.30.0.STABLE001/
  build.properties  ccw  epl-v10.html  icons  lein  leiningen16x16.png  leiningen32x32.png  leiningen-new-project.png  leiningen-standalone.jar  lib  META-INF  plugin.properties  plugin.xml
- Attached the .log file (dot-log.txt)

**Comment by roti** [comment]
I just installed CCW 0.31.1.STABLE001 in Eclipse Indigo (3.7.2) and I get the same exception when opening a clojure file.

```
Caused by: java.lang.Exception: namespace 'ccw.events' not found, compiling:(ccw/editors/clojure/editor_support.clj:11:1)
	at clojure.core$throw_if.doInvoke(core.clj:5405)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.core$load_lib.doInvoke(core.clj:5491)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at ccw.editors.clojure.editor_support$eval5213$loading__4958__auto____5214.invoke(editor_support.clj:11)
	at ccw.editors.clojure.editor_support$eval5213.invoke(editor_support.clj:11)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at ccw.util.osgi.ClojureOSGi$1.run(ClojureOSGi.java:92)
	... 95 more
Caused by: java.lang.Exception: namespace 'ccw.events' not found
	... 127 more
```

**Comment by laurentpetit** [comment]
Well, Eclipse Indigo is not supported anymore. Maybe `ccw.events` depends on an eclipse 4 feature which prevents it to be loaded?

**Comment by roti** [comment]
Well, thats fine then. I guess it makes no sense to investigate it. Downloading Luna is much easier. :)
It would help though, if you update the [web site](http://doc.ccw-ide.org/documentation.html#install-as-plugin) with this info.

**Comment by laurentpetit** [comment]
My bad !
The doc sources have been updated a long time ago, but I forgot it will
automatically become visible only when a new version is released!

Thanks for reminding me!

Le mardi 31 mars 2015, Răzvan Rotaru <notifications@github.com> a écrit :

> Well, thats fine then. I guess it makes no sense to investigate it.
> Downloading Luna is much easier. :)
> It would help though, if you update the web site
> <http://doc.ccw-ide.org/documentation.html#install-as-plugin> with this
> info.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/719#issuecomment-87967442>.
>


-- 
Laurent Petit
