### ISSUE TITLE
Finalize the implementation of the Eclipse Trace integration

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#743]
Currently most of the code seems there, but unused (so maybe not tested well enough), and with no directions on how to properly use it:

- from a developer's POV
   - [x] how to add a new kind of trace, and declare it
   - [x] how to use the API, what to expect in terms of added value
- from a user's POV
   - [x] how to enable and use tracing
   - [x] how to find the traces and send them to the Counterclockwise Team

**Comment by laurentpetit** [comment]
It seems like the plugins enabling tracing are not present in `CCW/Standalone`

**Comment by laurentpetit** [comment]
Some links to help think about it:
- http://www.vogella.com/tutorials/EclipseCodeAccess/article.html#tracing
- https://wiki.eclipse.org/FAQ_How_do_I_use_the_platform_debug_tracing_facility
- http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Flaunchers%2Ftracing.htm
- https://wiki.eclipse.org/FAQ_How_do_I_use_the_platform_debug_tracing_facility%3F
- https://ramblingabout.wordpress.com/2007/10/20/tracing-plug-ins-in-eclipse/
- http://www.winklerweb.net/index.php/blog/12-eclipse/10-finding-the-almost-new-eclipse-tracing-api
- http://blog.ankursharma.org/2011/12/osgi-tracing-in-equinox.html
- http://stackoverflow.com/questions/27492820/enable-tracing-for-a-plugin-in-eclipse-install

**Comment by arichiardi** [comment]
:+1:

**Comment by laurentpetit** [comment]
This feature is almost complete, I really just need to do debugging on it, and also consult the above articles to see whether I missed smth or did smth wrong.

I intend to work on it while waiting a little bit more for feedback on the `cider-nrepl` support. If no feedback at all or only positive feedback, I will consider releasing CCW with `cider-nrepl` merged into master (which also contains some interesting bug fixes).

**Comment by arichiardi** [comment]
Ok, I have tried it and here is an exception:

    Caused by: java.lang.NullPointerException
	at ccw.debug.serverrepl$textmate_filter.invoke(serverrepl.clj:165)
	at ccw.debug.serverrepl$textmate_filter.invoke(serverrepl.clj:161)
	at ccw.debug.serverrepl$textmate_distance.invoke(serverrepl.clj:176)
	at ccw.debug.serverrepl$distance_comparator$fn__6117.invoke(serverrepl.clj:213)
	at ccw.debug.serverrepl$distance_comparator$fn__6117.invoke(serverrepl.clj:223)
	at ccw.editors.clojure.clojure_proposal_processor$adapt_args$fn__6702.invoke(clojure_proposal_processor.clj:359)
	at clojure.lang.AFunction.compare(AFunction.java:47)
	at clojure.lang.PersistentTreeMap.doCompare(PersistentTreeMap.java:311)
	at clojure.lang.PersistentTreeMap.entryAt(PersistentTreeMap.java:298)
	at clojure.lang.PersistentTreeMap.containsKey(PersistentTreeMap.java:94)
	at clojure.lang.APersistentSet.contains(APersistentSet.java:34)
	at clojure.lang.PersistentTreeSet.cons(PersistentTreeSet.java:52)
	at clojure.lang.PersistentTreeSet.create(PersistentTreeSet.java:35)
	at clojure.core$sorted_set_by.doInvoke(core.clj:414)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:630)
	at ccw.editors.clojure.clojure_proposal_processor$compute_completion_proposals.invoke(clojure_proposal_processor.clj:389)
	at ccw.editors.clojure.clojure_proposal_processor$make_process$reify__6741.computeCompletionProposals(clojure_proposal_processor.clj:463)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:498)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:492)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:378)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3717)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3366)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

**Comment by arichiardi** [comment]
BTW what it says [here](http://blog.ankursharma.org/2011/12/osgi-tracing-in-equinox.html) is very interesting:
<quote>
<b>What do you mean by dynamic?</b>
If you notice, the debug options can be loaded at the launch time (using -osgi.debug) or programatically when running. However, if you wish to turn the tracing on/off in a running product, its tricky. PDE will be providing an extension using which a plug-in can expose its debug option flags. The UI will display these flags in preferences where they can be turned on/off for a running application. Cool! isn't it?</quote>

**Comment by laurentpetit** [comment]
Yes, this is cool, and indeed is what I expect to do.
I noticed that CCW/Standalone does not display a "Tracing" tab at all in the Preferences, so I may not have included some basic Eclipse plugins / features.
Also, the code was written a long time ago, when I was still maintaining 3.X compatibility. Now that we just need to be 4.X compatible, I want to revisit the code to see if it can be simplified, or could use newer APIs, etc.

**Comment by laurentpetit** [comment]
`org.eclipse.equinox.trace.ui` may be the missing Eclipse plugin

**Comment by laurentpetit** [comment]
Controlling the trace log: 
```
eclipse.trace.size.max : The system property used to specify size a trace file can grow before it is rotated
eclipse.trace.backup.max : The system property used to specify the maximum number of backup trace files to use
```

from http://blog.ankursharma.org/2011/12/osgi-tracing-in-equinox.html

**Comment by arichiardi** [comment]
I am having a look at this, I added the extension point and tried to enable some simple tracing. In a Kepler instance I have, where I exported (important!) ccw's plugins to, I receive the following...is it because of the exporting?

    log/error: ERROR  - ccw.core plugin should be deployed as a directory. This is a regression. Cannot locate file lein

    !ENTRY ccw.core 4 0 2015-04-18 18:57:09.173
    !MESSAGE ccw.core plugin should be deployed as a directory. This is a regression. Cannot locate file lein
    Exception in thread "Thread-11" java.lang.NullPointerException
	at ccw.leiningen.launch$lein_launch_configuration.invoke(launch.clj:39)
	at ccw.leiningen.launch$lein_launch_configuration.invoke(launch.clj:13)
	at clojure.lang.Var.invoke(Var.java:383)
	at ccw.util.ClojureUtils.invoke(ClojureUtils.java:46)
	at ccw.util.ClojureInvoker._(ClojureInvoker.java:26)
	at ccw.launching.ClojureLaunchShortcut.createLeiningenLaunchConfiguration(ClojureLaunchShortcut.java:276)
	at ccw.launching.ClojureLaunchShortcut.launchProject(ClojureLaunchShortcut.java:220)
	at ccw.launching.ClojureLaunchShortcut.launchProjectCheckRunning(ClojureLaunchShortcut.java:179)
	at ccw.launching.ClojureLaunchShortcut$3.run(ClojureLaunchShortcut.java:151)

**Comment by laurentpetit** [comment]
It may be because of exporting but I can't really wrap my head around the
issue.

I've started to rework / simplify the code locally. I will try to create a
pull request with the changes sometime during next week (will be on
holidays, so not sure when)

Le samedi 18 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> I am having a look at this, I added the extension point and tried to
> enable some simple tracing. In a Kepler instance I have, where I exported
> (important!) ccw's plugins to, I receive the following...is it because of
> the exporting?
>
> log/error: ERROR  - ccw.core plugin should be deployed as a directory. This is a regression. Cannot locate file lein
>
> !ENTRY ccw.core 4 0 2015-04-18 18:57:09.173
> !MESSAGE ccw.core plugin should be deployed as a directory. This is a regression. Cannot locate file lein
> Exception in thread "Thread-11" java.lang.NullPointerException
> at ccw.leiningen.launch$lein_launch_configuration.invoke(launch.clj:39)
> at ccw.leiningen.launch$lein_launch_configuration.invoke(launch.clj:13)
> at clojure.lang.Var.invoke(Var.java:383)
> at ccw.util.ClojureUtils.invoke(ClojureUtils.java:46)
> at ccw.util.ClojureInvoker._(ClojureInvoker.java:26)
> at ccw.launching.ClojureLaunchShortcut.createLeiningenLaunchConfiguration(ClojureLaunchShortcut.java:276)
> at ccw.launching.ClojureLaunchShortcut.launchProject(ClojureLaunchShortcut.java:220)
> at ccw.launching.ClojureLaunchShortcut.launchProjectCheckRunning(ClojureLaunchShortcut.java:179)
> at ccw.launching.ClojureLaunchShortcut$3.run(ClojureLaunchShortcut.java:151)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/743#issuecomment-94181698>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Yes, it was like that :) It is a little bit tricky, the options can change and it is passing in the listener, but nothing changes in the trace conf, I will investigate...

**Comment by laurentpetit** [comment]
Hi @arichiardi this PR seems ready for integration to me. Can you find time to test or code review it?

**Comment by arichiardi** [comment]
This one has still some problem...I have noticed that the tracing from all the clj files are not shown (the one traced through ```ccw.core.trace```. I have noticed that you prepended a slash in TraceOptions...maybe this has broken the keyword->string mapping inside the clojure tracer?
I am going to try something and get back to you...

**Comment by arichiardi** [comment]
In a Repl I tried:
```(-> (ccw.CCWPlugin/getTracer) (.trace ccw.TraceOptions/LOG_INFO "Ciao."))```

And it spit out:

    ClassCastException Cannot cast java.lang.String to [Ljava.lang.Object;  java.lang.Class.cast (Class.java:3176)```

Is it because it cannot cast to the trace signature:
    @Override
    public void trace(String traceOption, Object... message) {


?

**Comment by laurentpetit** [comment]
In the REPL for the first example, you should have put the String inside an array, something like
`(-> (ccw.CCWPlugin/getTracer) (.trace ccw.TraceOptions/LOG_INFO (into-array "Ciao.")))`

**Comment by arichiardi** [comment]
Found the problem, fix coming.

**Comment by laurentpetit** [comment]
ok thanks. This is a rather amusing piece of code, because generally when fixing something on the clojure side, I also broke something on the java side :-)

**Comment by arichiardi** [comment]
Yes, you did, but it's part of the game I guess :D

**Comment by arichiardi** [comment]
Almost finished, sorry but it was macro time for me :)
