### ISSUE TITLE
Ouline error: widget is disposed

### ISSUE THREAD

**Issue by arichiardi** [laurentpetit/ccw#788]
Hello Laurent, I am reporting this issue here to keep track of it.
I saw it a couple of times when coding, but it was sporadic.

Yesterday I push a commit on the ```osgi-fixes``` branch and now (I don't know if it's linked, I will need to investigate) it looks like Travis CI shows it during the tests.

The error logs:

      !ENTRY org.eclipse.core.jobs 4 2 2015-06-01 08:19:17.983
      !MESSAGE An internal error occurred during: "Outline browser tree refresh".
      !STACK 0
      java.lang.RuntimeException: org.eclipse.swt.SWTException: Widget is disposed
	at ccw.editors.outline.ClojureOutlinePage$2.run(ClojureOutlinePage.java:310)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
      Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4457)
	at org.eclipse.swt.SWT.error(SWT.java:4372)
	at org.eclipse.swt.SWT.error(SWT.java:4343)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:562)
	at ccw.editors.outline.ClojureOutlinePage.setInputInUiThread(ClojureOutlinePage.java:363)
	at ccw.editors.outline.ClojureOutlinePage$2.run(ClojureOutlinePage.java:307)
	... 1 more

      org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
	at org.eclipse.swt.SWT.error(SWT.java:4457)
	at org.eclipse.swt.SWT.error(SWT.java:4372)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3778)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3416)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:638)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:582)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
      Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4457)
	at org.eclipse.swt.SWT.error(SWT.java:4372)
	at org.eclipse.swt.SWT.error(SWT.java:4343)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:413)
	at org.eclipse.swt.widgets.Decorations.getMenuBar(Decorations.java:397)
	at org.eclipse.swtbot.swt.finder.finders.MenuFinder$1.run(MenuFinder.java:106)
	at org.eclipse.swtbot.swt.finder.finders.MenuFinder$1.run(MenuFinder.java:1)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$2.doRun(UIThreadRunnable.java:140)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:89)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 27 more

**Comment by laurentpetit** [comment]
:+1: Also seen this before, and pretended not having ... :) Will include in 0.32.0 milestone at least for qualif, if not correction.

**Comment by arichiardi** [comment]
Ahah lol :smiley: because I did the same

**Comment by laurentpetit** [comment]
I added an `isDisposed()` check in the culprit line, after the `is null` check.

**Comment by laurentpetit** [comment]
Mind you, it seems that the tests passed on my laptop....

**Comment by arichiardi** [comment]
I am going to check as well

**Comment by arichiardi** [comment]
Laurent...Did you checkout ```ccw.core/.settings/org.eclipse.jdt.ui.prefs``` by any chance? I cannot pull anymore...it complains about it.

**Comment by laurentpetit** [comment]
Yes, we were having editing conflicts on it, so i thought it would be
interesting to "impose" a standard (for spaces instead of tabs, etc.), but
maybe it's too problematic?

2015-06-12 14:25 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Laurent...Did you checkout ccw.core/.settings/org.eclipse.jdt.ui.prefs by
> any chance? I cannot pull anymore...it complains about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/788#issuecomment-111475711>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
I noticed it too, i always try to setup my ides to use spaces and I must have touched that file. I will try to keep my changes locally...it is good to impose standards, especially about indentation issues but what I try to do now, together with following project's standards, is to ```git add --patch``` as much as I can so that I don't spread my mess around :smile:

**Comment by arichiardi** [comment]
Big ```SUCCESS``` on this side as well.

**Comment by laurentpetit** [comment]
Well, mitigated in mine after several tests. Still unstable, sometimes
working, sometimes not. Still not working in Jenkins, also.

Le vendredi 12 juin 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Big SUCCESS on this side as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/788#issuecomment-111488193>.
>


-- 
Laurent Petit
