### ISSUE TITLE
can't launch REPL in STS 3.7.0.RELEASE Build Id: 201506290652 Platform: Eclipse Mars (4.5.0)

### ISSUE THREAD

**Issue by The-Alchemist** [laurentpetit/ccw#832]
When trying "Run As Clojure Application", I get two errors in the Eclipse Error Log:

```
eclipse.buildId=3.7.0.201506290652-RELEASE-e45
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -keyring /Users/the-alchemist/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.springsource.sts.ide -data file:/Users/the-alchemist/Documents/workspaces/something/ -product org.springsource.sts.ide -keyring /Users/the-alchemist/.eclipse_keyring -showlocation

org.eclipse.e4.ui.workbench
Error
Sat Aug 01 23:57:56 EDT 2015
Internal error during tool item enablement updating, this is only logged once per tool item.

org.eclipse.e4.core.di.InjectionException: java.lang.IllegalAccessException: Class org.eclipse.e4.core.internal.di.MethodRequestor can not access a member of class org.eclipse.ui.internal.handlers.E4HandlerProxy with modifiers ""
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:60)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:80)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:875)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:179)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.canExecuteItem(HandledContributionItem.java:813)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$1(HandledContributionItem.java:802)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$3.run(HandledContributionItem.java:167)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.updateItemEnablement(HandledContributionItem.java:198)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolItemUpdater.updateContributionItems(ToolItemUpdater.java:37)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.subscribeTopicUpdateToolbarEnablement(ToolBarManagerRenderer.java:298)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:56)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.IllegalAccessException: Class org.eclipse.e4.core.internal.di.MethodRequestor can not access a member of class org.eclipse.ui.internal.handlers.E4HandlerProxy with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:490)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 43 more

```

And then:
```
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalAccessException: Class org.eclipse.e4.core.internal.di.MethodRequestor can not access a member of class org.eclipse.ui.internal.handlers.E4HandlerProxy with modifiers ""
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:60)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:80)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:875)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:179)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.canExecuteItem(HandledContributionItem.java:813)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$1(HandledContributionItem.java:802)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$3.run(HandledContributionItem.java:167)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.updateItemEnablement(HandledContributionItem.java:198)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolItemUpdater.updateContributionItems(ToolItemUpdater.java:37)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.subscribeTopicUpdateToolbarEnablement(ToolBarManagerRenderer.java:298)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:56)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.IllegalAccessException: Class org.eclipse.e4.core.internal.di.MethodRequestor can not access a member of class org.eclipse.ui.internal.handlers.E4HandlerProxy with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:490)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 43 more

```

Not sure if this is a Eclipse Mars thing.

If someone points me in the right direction, I can probably submit a pull request. :)

# STS Details

3.7.0.RELEASE
Build Id: 201506290652
Platform: Eclipse Mars (4.5.0)

# More Details
Oracle Java 1.8.0_51
Mac OS X Yosemite 10.10.4 (14E46)

**Comment by laurentpetit** [comment]
Wow, the error is really weird, and does not seem, at least directly, related to a problem of not being able to open a REPL.
Will have to download STS to try to reproduce the problem.
No idea at all of what could happen / how to solve it, at the moment.

**Comment by The-Alchemist** [comment]
It might have to do with something specific to this project.  I'll play around with it tomorrow.

**Comment by laurentpetit** [comment]
I'm sorry, I tried to reproduce the problem : I have downloaded STS 3.7.0, am using OS X Yosemite 10.10.4 (14E46) and Oracle Java "1.8.0_45".
So very close to your configuration.

Without installing anything else in STS, I installed CCW from http://updatesite.ccw-ide.org/stable

I have been able to create a new clojure project, and then, start a REPL for it using 2 different ways:
- from the contextual menu in the clojure editor
- from the Run as > Clojure Application (preload file) in the context menu of the clojure file's node in the project explorer.

Also, I didn't see any exception while launching the REPL.

**Comment by The-Alchemist** [comment]
Sorry, @laurentpetit, my bad.  I forgot to mention that this isn't a "Clojure Project" per se.  It's a regular Maven Java app with clojure 1.7.0 as a "test" scope dependency.

I'm currently working on a skeleton Maven project that'll reproduce this.

**Comment by laurentpetit** [comment]
That'll be great, thanks!

2015-08-03 23:35 GMT+02:00 The Alchemist <notifications@github.com>:

> Sorry, @laurentpetit <https://github.com/laurentpetit>, my bad. I forgot
> to mention that this isn't a "Clojure Project" per se. It's a regular Maven
> Java app with clojure 1.7.0 as a "test" scope dependency.
>
> I'm currently working on a skeleton Maven project that'll reproduce this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/832#issuecomment-127411749>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
In the mean time, I'll try to reproduce it anyway: playing with the Clojure Preferences, it's possible to tell the launcher to not use leiningen, nor cider (may that matter) for launching your project, but rather just use what's in the java build path (no matter how it's been populated), load ccw.server dynamically (to still get repl completion, etc. goodness), and then just start clojure.main.

That should be more or less what is done by default for a project which hasn't been detected as a leiningen project, but still has a clojure jar in its classpath.

**Comment by laurentpetit** [comment]
No, I still cannot reproduce locally. Will wait for your small reproducible maven project.

**Comment by The-Alchemist** [comment]
My apologies, I can't isolate the problem.  I even tried importing CCW into my workspace, launching a new instance of the CCW Plugin, and importing the offending project--and everything works fine. :(

Well, not sure if it's helpful, but I have the log for when it's misbehaving.  Closing for now.

```

!ENTRY ccw.core 1 0 2015-08-03 18:51:38.310
!MESSAGE Stopping ccw nREPL server...
!SESSION 2015-08-03 18:51:40.495 -----------------------------------------------
eclipse.buildId=3.7.0.201506290652-RELEASE-e45
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -keyring /Users/the-alchemist/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.springsource.sts.ide -product org.springsource.sts.ide -data file:/Users/the-alchemist/Documents/workspaces/workspace/ -product org.springsource.sts.ide -keyring /Users/the-alchemist/.eclipse_keyring -showlocation

!ENTRY ccw.core 1 0 2015-08-03 18:51:43.274
!MESSAGE CCWPlugin.start(): ENTER

!ENTRY ccw.core 1 0 2015-08-03 18:51:43.960
!MESSAGE Counterclockwise dependencies:
        [bultitude "0.2.1"]
        [ccw/ccw.server "0.2.0"]
        [ccw/clojure-ccw "1.7.0"]
        [cheshire "5.0.2"]
        [classlojure "0.6.6"]
        [clj-http "0.9.2"]
        [clj-stacktrace "0.2.7"]
        [clj-tuple "0.1.2"]
        [clojure-complete "0.2.3"]
        [com.cemerick/drawbridge "0.0.6"]
        [com.cemerick/pomegranate "0.3.0"]
        [com.fasterxml.jackson.core/jackson-core "2.1.3"]
        [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.1.2"]
        [com.hypirion/io "0.3.1"]
        [commons-codec "1.9"]
        [commons-fileupload "1.2.1"]
        [commons-io "2.4"]
        [commons-lang "2.6"]
        [commons-logging "1.1.3"]
        [dynapath "0.2.0"]
        [jline "2.12"]
        [leiningen "2.5.1"]
        [leiningen-core "2.5.1"]
        [net.cgrand/parsley "0.9.2"]
        [net.cgrand/regex "1.1.0"]
        [net.cgrand/sjacket "0.1.1"]
        [net.mikera/cljunit "0.2.0"]
        [org.apache.httpcomponents/httpclient "4.3.3"]
        [org.apache.httpcomponents/httpcore "4.3.2"]
        [org.apache.httpcomponents/httpmime "4.3.3"]
        [org.apache.maven/maven-aether-provider "3.0.4"]
        [org.apache.maven/maven-model "3.0.4"]
        [org.apache.maven/maven-model-builder "3.0.4"]
        [org.apache.maven/maven-repository-metadata "3.0.4"]
        [org.apache.maven.indexer/indexer-artifact "4.1.3"]
        [org.apache.maven.indexer/indexer-core "4.1.3"]
        [org.apache.maven.wagon/wagon-http "2.7"]
        [org.apache.maven.wagon/wagon-http-shared "2.7"]
        [org.apache.maven.wagon/wagon-provider-api "2.2"]
        [org.clojure/clojure-contrib "1.2.0"]
        [org.clojure/core.incubator "0.1.0"]
        [org.clojure/data.xml "0.0.3"]
        [org.clojure/java.classpath "0.2.2"]
        [org.clojure/java.data "0.1.1"]
        [org.clojure/tools.cli "0.3.1"]
        [org.clojure/tools.logging "0.2.3"]
        [org.clojure/tools.macro "0.1.1"]
        [org.clojure/tools.nrepl "0.2.10"]
        [org.clojure/tools.reader "0.8.4"]
        [org.codehaus.plexus/plexus-classworlds "2.4"]
        [org.codehaus.plexus/plexus-component-annotations "1.5.5"]
        [org.codehaus.plexus/plexus-interpolation "1.14"]
        [org.codehaus.plexus/plexus-utils "2.0.6"]
        [org.jsoup/jsoup "1.7.2"]
        [org.sonatype.aether/aether-api "1.13.1"]
        [org.sonatype.aether/aether-connector-file "1.13.1"]
        [org.sonatype.aether/aether-connector-wagon "1.13.1"]
        [org.sonatype.aether/aether-impl "1.13.1"]
        [org.sonatype.aether/aether-spi "1.13.1"]
        [org.sonatype.aether/aether-util "1.13.1"]
        [org.sonatype.sisu/sisu-inject-bean "2.2.3"]
        [org.sonatype.sisu/sisu-inject-plexus "2.2.3"]
        [org.tcrawley/dynapath "0.2.3"]
        [pedantic "0.2.0"]
        [potemkin "0.3.4"]
        [quoin "0.1.2"]
        [reply "0.3.5"]
        [riddley "0.1.6"]
        [ring/ring-core "1.0.2"]
        [robert/hooke "1.3.0"]
        [scout "0.1.0"]
        [slingshot "0.10.3"]
        [stencil "0.3.5"]
        [trptcolin/versioneer "0.1.1"]

!ENTRY ccw.core 1 0 2015-08-03 18:51:47.634
!MESSAGE CCWPlugin.start(): EXIT

!ENTRY org.eclipse.jface 2 0 2015-08-03 18:51:49.973
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-08-03 18:51:49.974
!MESSAGE A conflict occurred for COMMAND+SHIFT+F10:
Binding(COMMAND+SHIFT+F10,
	ParameterizedCommand(Command(org.jboss.tools.common.ui.RegisterAsService,Register As Service,
		Adds class name to META-INF/services/%serviceType% file after service type is selected in the dialog from types extended and implemented by the class.,
		Category(org.eclipse.ui.category.file,File,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5ad67d82,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(COMMAND+SHIFT+F10,
	ParameterizedCommand(Command(org.eclipse.ui.window.showSystemMenu,Show System Menu,
		Show the system menu,
		Category(org.eclipse.ui.category.window,Window,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@301608d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-08-03 18:51:49.974
!MESSAGE A conflict occurred for ALT+COMMAND+Z:
Binding(ALT+COMMAND+Z,
	ParameterizedCommand(Command(org.jboss.tools.cdi.ui.open.namedBean,Open CDI Named Bean...,
		Open CDI Named Bean...,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3c3a8246,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+Z,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.surround.with.quickMenu,Surround With Quick Menu,
		Shows the Surround With quick menu,
		Category(org.eclipse.jdt.ui.category.source,Source,Java Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@bd8f424,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.438
!MESSAGE Loaded User Script /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-ansi-repl/ansi-repl.clj

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.441
!MESSAGE Loaded User Plugin: /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-ansi-repl

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.484
!MESSAGE Loaded User Script /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-hello-world/hello-world.clj

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.484
!MESSAGE Loaded User Plugin: /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-hello-world

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.609
!MESSAGE Loaded User Script /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-manager/ccw-plugin-manager.clj

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.610
!MESSAGE Loaded User Plugin: /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-manager

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.712
!MESSAGE Loaded User Script /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-zoom/ccw-plugin-zoom.clj

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.713
!MESSAGE Loaded User Plugin: /Users/the-alchemist/Applications/sts-bundle/STS.app/Contents/Eclipse/plugins/ccw.core_0.32.0.STABLE002/ccw-plugins/ccw-plugin-zoom

!ENTRY ccw.core 1 0 2015-08-03 18:51:58.713
!MESSAGE Loaded User Plugins

!ENTRY ccw.core 1 0 2015-08-03 18:52:42.853
!MESSAGE putting in launchNameREPLURLPromiseAndWithREPLView the key: com.thealchemist.kp-ejb REPL #1

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-08-03 18:52:48.612
!MESSAGE No repository found at http://download.eclipse.org/releases/.

```

**Comment by laurentpetit** [comment]
OK.
Nothing wrong per see in the last log.
